apiVersion: v1
kind: Service
metadata:
  name: mqtt-lb
  namespace: esp32-rhte
spec:
  ports:
  - name: mqtt-lb
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    ActiveMQArtemis: mqtt
    application: mqtt-app
  type: LoadBalancer
